var Profiles=[
	{
		'Name':'Рим',
		'File':'roma.jpg',
		'pointarr':'romaPt',
		'offsetTop':'-377px',
		'offsetLeft':'-840px',
		'StartIndex':1,
		'zoom':1,
		'GpoupList':'\
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"> \
		<span class="icon"></span><span class="text">&nbsp;Флаги</span></h4> \
		</div> \
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"> \
		<span class="icon"></span><span class="text">&nbsp;Метки с глазом</span></h4> \
		</div> \
		<div href="#" class="list-group-item"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;Перья</span></h4> \
		</div> \
		<div href="#" class="list-group-item autohist"> \
		<h4 class="list-group-item-heading"><span class="icon"></span><span class="text">&nbsp;История</span></h4> \
		</div> \
		',
	},
];
var romaPt=[
	{
		'Name':'На крыше колизея',
		'CoordX':'2092px',
		'CoordY':'1464px',
		'Groups':'[0]',
	},
	{
		'Name':'Перо на крыше колизея',
		'CoordX':'1896px',
		'CoordY':'1343px',
		'Groups':'[2]',
	},
	{
		'Name':'На стене колизея, вход сверху',
		'CoordX':'1946px',
		'CoordY':'1293px',
		'Groups':'[1]',
	},
	{
		'Name':'На балке, около капитана боржиа',
		'CoordX':'1085px',
		'CoordY':'497px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше дома куртизанок',
		'CoordX':'1040px',
		'CoordY':'745px',
		'Groups':'[0]',
	},
	{
		'Name':'На стене дома куртизанок',
		'CoordX':'1017px',
		'CoordY':'713px',
		'Groups':'[1]',
	},
	{
		'Name':'На колонее, около тоннеля перемещения',
		'CoordX':'1098px',
		'CoordY':'1290px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, на балке',
		'CoordX':'1733px',
		'CoordY':'878px',
		'Groups':'[0]',
	},
	{
		'Name':'На острове, внизу.',
		'CoordX':'2272px',
		'CoordY':'979px',
		'Groups':'[0]',
	},
	{
		'Name':'На стене смотровой башни',
		'CoordX':'1589px',
		'CoordY':'116px',
		'Groups':'[1]',
	},
	{
		'Name':'На балках между домами',
		'CoordX':'1610px',
		'CoordY':'151px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне',
		'CoordX':'1388px',
		'CoordY':'1752px',
		'Groups':'[0]',
	},
	{
		'Name':'На шпиле, на самой верхней точке.',
		'CoordX':'1089px',
		'CoordY':'196px',
		'Groups':'[0]',
	},
	{
		'Name':'Флаг на крыше, в развалинах дома',
		'CoordX':'989px',
		'CoordY':'1158px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонее',
		'CoordX':'1030px',
		'CoordY':'1423px',
		'Groups':'[0]',
	},
	{
		'Name':'На самой верхней колонне',
		'CoordX':'1938px',
		'CoordY':'387px',
		'Groups':'[0]',
	},
	{
		'Name':'На самой верхней колонне, на западе от тоннеля',
		'CoordX':'1846px',
		'CoordY':'419px',
		'Groups':'[0]',
	},
	{
		'Name':'Сложный флаг на колонне',
		'CoordX':'1876px',
		'CoordY':'495px',
		'Groups':'[0]',
	},
	{
		'Name':'На балке, на стене дома',
		'CoordX':'1864px',
		'CoordY':'544px',
		'Groups':'[0]',
	},
	{
		'Name':'Перо на крыше дома',
		'CoordX':'1850px',
		'CoordY':'345px',
		'Groups':'[2]',
	},
	{
		'Name':'На балке, на стене дома',
		'CoordX':'1690px',
		'CoordY':'381px',
		'Groups':'[0]',
	},
	{
		'Name':'На козырьке дома',
		'CoordX':'1491px',
		'CoordY':'237px',
		'Groups':'[0]',
	},
	{
		'Name':'На балке, на стене дома.',
		'CoordX':'1476px',
		'CoordY':'61px',
		'Groups':'[0]',
	},
	{
		'Name':'На балке здания',
		'CoordX':'1753px',
		'CoordY':'207px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, на балке, в квадрате.',
		'CoordX':'1681px',
		'CoordY':'520px',
		'Groups':'[0]',
	},
	{
		'Name':'Перо на крыше',
		'CoordX':'1529px',
		'CoordY':'351px',
		'Groups':'[2]',
	},
	{
		'Name':'На балке, на стене дома, у моря',
		'CoordX':'1457px',
		'CoordY':'382px',
		'Groups':'[0]',
	},
	{
		'Name':'Между домами, на балке',
		'CoordX':'1241px',
		'CoordY':'566px',
		'Groups':'[0]',
	},
	{
		'Name':'Перо на крыше, на кресте',
		'CoordX':'1429px',
		'CoordY':'680px',
		'Groups':'[2]',
	},
	{
		'Name':'Внутри пантеона, у двери.',
		'CoordX':'1435px',
		'CoordY':'706px',
		'Groups':'[1]',
	},
	{
		'Name':'На крыше, 1 ур.',
		'CoordX':'1561px',
		'CoordY':'696px',
		'Groups':'[0]',
	},
	{
		'Name':'На балках, между домами',
		'CoordX':'1677px',
		'CoordY':'750px',
		'Groups':'[0]',
	},
	{
		'Name':'Перо на крыше.',
		'CoordX':'1609px',
		'CoordY':'1078px',
		'Groups':'[2]',
	},
	{
		'Name':'На стене, с видом на обрыв.',
		'CoordX':'1641px',
		'CoordY':'1103px',
		'Groups':'[1]',
	},
	{
		'Name':'На колонне',
		'CoordX':'1637px',
		'CoordY':'1147px',
		'Groups':'[0]',
	},
	{
		'Name':'На балках, между домами',
		'CoordX':'1538px',
		'CoordY':'925px',
		'Groups':'[0]',
	},
	{
		'Name':'На помосте, на стене здания.',
		'CoordX':'1385px',
		'CoordY':'996px',
		'Groups':'[0]',
	},
	{
		'Name':'На балках, между домами',
		'CoordX':'1151px',
		'CoordY':'970px',
		'Groups':'[0]',
	},
	{
		'Name':'На балке, со стороны двора.',
		'CoordX':'1175px',
		'CoordY':'815px',
		'Groups':'[0]',
	},
	{
		'Name':'Высоко на шпиле (кресте).',
		'CoordX':'1365px',
		'CoordY':'711px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, рядом с голубятней',
		'CoordX':'1313px',
		'CoordY':'1179px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонее',
		'CoordX':'1211px',
		'CoordY':'1281px',
		'Groups':'[0]',
	},
	{
		'Name':'Флаг на колонне',
		'CoordX':'815px',
		'CoordY':'1127px',
		'Groups':'[0]',
	},
	{
		'Name':'Перо',
		'CoordX':'902px',
		'CoordY':'1033px',
		'Groups':'[2]',
	},
	{
		'Name':'Перо на колонне.',
		'CoordX':'1687px',
		'CoordY':'1239px',
		'Groups':'[2]',
	},
	{
		'Name':'Перо на колонне',
		'CoordX':'2139px',
		'CoordY':'1503px',
		'Groups':'[2]',
	},
	{
		'Name':'На колонне',
		'CoordX':'1973px',
		'CoordY':'481px',
		'Groups':'[0]',
	},
	{
		'Name':'На самой верхней колонне',
		'CoordX':'2033px',
		'CoordY':'406px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше рынка',
		'CoordX':'1823px',
		'CoordY':'1024px',
		'Groups':'[0]',
	},
	{
		'Name':'Перо на крыше казармы',
		'CoordX':'2417px',
		'CoordY':'947px',
		'Groups':'[2]',
	},
	{
		'Name':'Перо у французов на площадке',
		'CoordX':'2382px',
		'CoordY':'727px',
		'Groups':'[2]',
	},
	{
		'Name':'На стене смотровой башни.',
		'CoordX':'2612px',
		'CoordY':'1263px',
		'Groups':'[0]',
	},
	{
		'Name':'На башне',
		'CoordX':'2722px',
		'CoordY':'1225px',
		'Groups':'[0]',
	},
	{
		'Name':'Высоко, где акведук',
		'CoordX':'2404px',
		'CoordY':'1213px',
		'Groups':'[0]',
	},
	{
		'Name':'Флаг на колонне',
		'CoordX':'2453px',
		'CoordY':'1360px',
		'Groups':'[0]',
	},
	{
		'Name':'флаг на колонне',
		'CoordX':'1506px',
		'CoordY':'1464px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше башни',
		'CoordX':'2365px',
		'CoordY':'1766px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше дома, рядом с акведуком',
		'CoordX':'2432px',
		'CoordY':'1639px',
		'Groups':'[0]',
	},
	{
		'Name':'На акведуке, сбоку.',
		'CoordX':'2450px',
		'CoordY':'1672px',
		'Groups':'[1]',
	},
	{
		'Name':'На колонне',
		'CoordX':'2332px',
		'CoordY':'1567px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне, прыгаем с акведука',
		'CoordX':'2139px',
		'CoordY':'1667px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне, опять прыгаем с акведука',
		'CoordX':'1811px',
		'CoordY':'1657px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне, рядом с заданем от воров',
		'CoordX':'1365px',
		'CoordY':'1554px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне, рядом с голубятней',
		'CoordX':'979px',
		'CoordY':'1759px',
		'Groups':'[0]',
	},
	{
		'Name':'Флаг на колонне',
		'CoordX':'1110px',
		'CoordY':'1852px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне, где термы',
		'CoordX':'1625px',
		'CoordY':'2045px',
		'Groups':'[0]',
	},
	{
		'Name':'Наверху, на цветущей башне.',
		'CoordX':'1691px',
		'CoordY':'1982px',
		'Groups':'[0]',
	},
	{
		'Name':'Наверху, на колонне.',
		'CoordX':'1761px',
		'CoordY':'2018px',
		'Groups':'[0]',
	},
	{
		'Name':'флаг на стене развалин дома',
		'CoordX':'1973px',
		'CoordY':'1982px',
		'Groups':'[0]',
	},
	{
		'Name':'На акведуке',
		'CoordX':'1830px',
		'CoordY':'297px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше дома',
		'CoordX':'1805px',
		'CoordY':'313px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне, рядом с голубятней',
		'CoordX':'1950px',
		'CoordY':'456px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше башни',
		'CoordX':'2495px',
		'CoordY':'538px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, во фр. лагере',
		'CoordX':'2631px',
		'CoordY':'649px',
		'Groups':'[0]',
	},
	{
		'Name':'На стене, у главных ворот фр. лагеря',
		'CoordX':'2711px',
		'CoordY':'697px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, уголок гл. фр. злодея',
		'CoordX':'2907px',
		'CoordY':'598px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне, во фр. лагере',
		'CoordX':'2358px',
		'CoordY':'704px',
		'Groups':'[0]',
	},
	{
		'Name':'Во фр. лагере, в арках.',
		'CoordX':'2359px',
		'CoordY':'786px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше дома',
		'CoordX':'2013px',
		'CoordY':'709px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше дома',
		'CoordX':'1850px',
		'CoordY':'898px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше дома, в лагере фр.',
		'CoordX':'2015px',
		'CoordY':'974px',
		'Groups':'[0]',
	},
	{
		'Name':'В крепости снайпера',
		'CoordX':'2245px',
		'CoordY':'894px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне, напротив колизея.',
		'CoordX':'2207px',
		'CoordY':'1343px',
		'Groups':'[0]',
	},
	{
		'Name':'На угловой колонне',
		'CoordX':'2296px',
		'CoordY':'1354px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне',
		'CoordX':'2342px',
		'CoordY':'1293px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше собора, рядом со входом',
		'CoordX':'2284px',
		'CoordY':'1090px',
		'Groups':'[0]',
	},
	{
		'Name':'На угловой колонне',
		'CoordX':'2812px',
		'CoordY':'1534px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне',
		'CoordX':'1455px',
		'CoordY':'1887px',
		'Groups':'[0]',
	},
	{
		'Name':'На колонне, около колизея',
		'CoordX':'1732px',
		'CoordY':'1358px',
		'Groups':'[0]',
	},
	{
		'Name':'На арке',
		'CoordX':'1832px',
		'CoordY':'1383px',
		'Groups':'[0]',
	},
	{
		'Name':'На стене башни',
		'CoordX':'1384px',
		'CoordY':'1718px',
		'Groups':'[1]',
	},
	{
		'Name':'На крыше кирпичного здания',
		'CoordX':'1825px',
		'CoordY':'1194px',
		'Groups':'[0]',
	},
	{
		'Name':'На палке, торчащей из воды.',
		'CoordX':'1178px',
		'CoordY':'261px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше, 1 уровень',
		'CoordX':'558px',
		'CoordY':'337px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше зданий',
		'CoordX':'704px',
		'CoordY':'272px',
		'Groups':'[0]',
	},
	{
		'Name':'На крыше дома',
		'CoordX':'769px',
		'CoordY':'296px',
		'Groups':'[0]',
	},
	{
		'Name':'На стене',
		'CoordX':'2947px',
		'CoordY':'630px',
		'Groups':'[1]',
	},
	{
		'Name':'На стене казармы',
		'CoordX':'2488px',
		'CoordY':'949px',
		'Groups':'[1]',
	},
	{
		'Name':'На стене балкона.',
		'CoordX':'1092px',
		'CoordY':'261px',
		'Groups':'[1]',
	},
]